spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.30.112:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.30.77
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.30.77
    port: 6379
env:
  test12
girl:
  name: lili
  age: 25